- name: Ajenti2
  hosts: all
  tasks:
    - name: Update and upgrade
      become: true
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
    - name: Install packages
      become: true
      ansible.builtin.apt:
        pkg:
          - build-essential
          - python3-pip
          - python3-venv
          - python3-dev
          - python3-lxml
          - libssl-dev
          - python3-dbus
          - python3-augeas
          - python3-apt
          - ntpdate
        state: present
        update_cache: true
        install_recommends: false
    - name: Create venv
      become: true
      ansible.builtin.shell:
        cmd: python3 -m venv /opt/ajenti --system-site-packages && source /opt/ajenti/bin/activate
        executable: /bin/bash
      register: output
      changed_when: output.rc != 0
    - name: Install ajenti2
      become: true
      ansible.builtin.pip:
        virtualenv: /opt/ajenti
        name:
          - ajenti-panel
          - ajenti.plugin.ace
          - ajenti.plugin.augeas
          - ajenti.plugin.auth-users
          - ajenti.plugin.core
          - ajenti.plugin.dashboard
          - ajenti.plugin.datetime
          - ajenti.plugin.filemanager
          - ajenti.plugin.filesystem
          - ajenti.plugin.network
          - ajenti.plugin.notepad
          - ajenti.plugin.packages
          - ajenti.plugin.passwd
          - ajenti.plugin.plugins
          - ajenti.plugin.power
          - ajenti.plugin.services
          - ajenti.plugin.settings
          - ajenti.plugin.terminal
